### ISSUE TITLE
Modify to turn on a relay?

### ISSUE THREAD

**Issue by pspfreak** [peckrob/petfeedd#23]
I have an existing pet feeder i've modified to run with a relay and pi, not a servo. Would it be possible to use this for that purpose instead?

**Comment by peckrob** [comment]
I think it should. All petfeedd is, really, is a fancy interface and a scheduler around GPIOZero. All it does is put power to a pin for a certain amount of time, on a schedule. Whether that pin is connected to a servo or a relay is really not something it knows about.

FWIW there is a big rewrite I have been working on over in the v0.2-working branch that I hope to launch soon. I will clarify some of these points in it. :)

**Comment by pspfreak** [comment]
Thank you, I'll give it a try!

**Comment by peckrob** [comment]
Version 1.0 explicitly includes support for using "Raw" devices now such as this. Feel free to open a new issue if this is not working for you.
