### ISSUE TITLE
Settings page blank

### ISSUE THREAD

**Issue by justinoreilly** [peckrob/petfeedd#4]
I just attempted to install petfeed on a Raspberry Pi 3 Model B, I had a bit of an issue with the dependencies but I seem to have gotten them resolved. Hashes did not match. I have an issue where I can get to petted via my web browser, but the settings page is blank with just the navigation banner displayed. Is this intended?

**Comment by peckrob** [comment]
Hi, thanks for reporting this issue. Glad to hear you got it installed!

Yes, it is blank right now. This is a placeholder for a future settings page. I have some commits to that effect if I can get around to rolling them out. :)

**Comment by justinoreilly** [comment]
Also, Here is the new hash for markupsafe

`"markupsafe": {
            "hashes": [
                "sha256:ece10100224e92dac2b971dbe006a47c8a180a5c65ad576844b6eef1a9eb0f68"
            ],
            "version": "==1.0"
        },
`
