### ISSUE TITLE
Issue reading GPIO

### ISSUE THREAD

**Issue by justinoreilly** [peckrob/petfeedd#5]
Upon starting petfeedd the service starts but unable to communicate with GPIO even though everything installs correctly.

`
root@petfeeder:/opt/petfeedd# tail -f /var/log/syslog 
Aug 21 22:16:28 petfeeder pipenv[2398]: /root/.local/share/virtualenvs/petfeedd-0kLIorXM/lib/python3.5/site-packages/gpiozero/devices.py:451: PinFactoryFallback: Falling back from rpigpio: No module named 'RPi'

Aug 21 22:16:28 petfeeder pipenv[2398]:   'Falling back from %s: %s' % (name, str(e))))

Aug 21 22:16:28 petfeeder pipenv[2398]: /root/.local/share/virtualenvs/petfeedd-0kLIorXM/lib/python3.5/site-packages/gpiozero/devices.py:451: PinFactoryFallback: Falling back from rpio: No module named 'RPIO'

Aug 21 22:16:28 petfeeder pipenv[2398]:   'Falling back from %s: %s' % (name, str(e))))

Aug 21 22:16:28 petfeeder pipenv[2398]: /root/.local/share/virtualenvs/petfeedd-0kLIorXM/lib/python3.5/site-packages/gpiozero/devices.py:451: PinFactoryFallback: Falling back from pigpio: No module named 'pigpio'

Aug 21 22:16:28 petfeeder pipenv[2398]:   'Falling back from %s: %s' % (name, str(e))))

Aug 21 22:16:28 petfeeder pipenv[2398]:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)

Aug 21 22:16:47 petfeeder pipenv[2398]: 10.204.33.126 - - [21/Aug/2018 22:16:47] "GET / HTTP/1.1" 200 -

Aug 21 22:16:47 petfeeder pipenv[2398]: 10.204.33.126 - - [21/Aug/2018 22:16:47] "GET /api/events HTTP/1.1" 200 -

Aug 21 22:16:47 petfeeder pipenv[2398]: 10.204.33.126 - - [21/Aug/2018 22:16:47] "GET /api/status HTTP/1.1" 200 -
`

**Comment by samuelthng** [comment]
I have the same issue.

gpiozero is accessible from OUTSIDE of the pipenv environment but not inside it.

**Comment by peckrob** [comment]
Going to go ahead and close this now. Feel free to create a another bug if it continues to be an issue.
