### ISSUE TITLE
Timezone in Docker

### ISSUE THREAD

**Issue by nabossha** [peckrob/petfeedd#6]
hey, very nice work with the docker-image :-D i am currently building a new cat-feeder using your code and so far it works perfect! 

i found one minor issue though:
the docker image seems not respect the local timezone of the raspberry:

- Pi is set to timezone `"Europe/Zurich"` using raspi-config
- `$ date` shows correct local date and time
- `$ docker run --privileged -v /opt/petfeedd.db:/petfeedd/petfeedd.db -v /etc/petfeedd.conf:/petfeedd/petfeedd.conf -p 0.0.0.0:8080:8080 peckrob/petfeedd-arm32v7` with logging=enabled shows all times from docker-container are 1 hour off (eg: local date on raspberry=23:10:33 - log-entry in docker-container = 22:10:33)

would be nice if there would be an option to respect this

**Comment by peckrob** [comment]
Hey, thanks for the report!
Yeah, timezones in Docker are kind of a pain. You might try mounting `/etc/localtime` into the Docker image? 

`docker run --privileged -v /etc/localtime:/etc/localtime -v /opt/petfeedd.db:/petfeedd/petfeedd.db -v /etc/petfeedd.conf:/petfeedd/petfeedd.conf -p 0.0.0.0:8080:8080 peckrob/petfeedd-arm32v7`

**Comment by peckrob** [comment]
Tested this at lunch today and confirmed it works. I'll update the documentation.

**Comment by nabossha** [comment]
confirmed - this works! thanks a lot :-D
